$primary = @{primary.rgb}
$primary_container = @{primary_container.rgb}
$secondary = @{secondary.rgb}
$tertiary = @{tertiary.rgb}
$surface = @{surface.rgb}
$surface_container = @{surface_container.rgb}
$error = @{error.rgb}
$on_surface = @{on_surface.rgb}
$outline = @{outline.rgb}
