-- Generated by Matugen
return {
    primary = "rgb({{colors.primary.default.hex_stripped}})",
    primary_container = "rgb({{colors.primary_container.default.hex_stripped}})",
    secondary = "rgb({{colors.secondary.default.hex_stripped}})",
    tertiary = "rgb({{colors.tertiary.default.hex_stripped}})",
    surface = "rgb({{colors.surface.default.hex_stripped}})",
    surface_container = "rgb({{colors.surface_container.default.hex_stripped}})",
    error = "rgb({{colors.error.default.hex_stripped}})",
    on_surface = "rgb({{colors.on_surface.default.hex_stripped}})",
    outline = "rgb({{colors.outline.default.hex_stripped}})",
}
