pragma Singleton

import QtQuick
import Quickshell

// Generated by matugen from templates/quickshell-colors.qml
// Do not edit directly -- edit the template and re-run matugen.
Singleton {
    // ---- surfaces (low to high elevation) ----
    readonly property color base: "{{colors.surface_container.default.hex}}"
    readonly property color mantle: "{{colors.surface_container_low.default.hex}}"
    readonly property color surface0: "{{colors.surface_container_high.default.hex}}"
    readonly property color surface1: "{{colors.surface_container_highest.default.hex}}"
    readonly property color outline: "{{colors.outline_variant.default.hex}}"

    // ---- text ----
    readonly property color textMain: "{{colors.on_surface.default.hex}}"
    readonly property color textDim: "{{colors.on_surface_variant.default.hex}}"
    readonly property color textFaint: "{{colors.outline.default.hex}}"

    // ---- accents ----
    // NB: do not name properties on<Capital> -- QML parses those as
    // signal handlers, not properties ("Cannot assign a value to a signal").
    // accentFg / dangerFg are the foreground colours to use *on top of*
    // an accent or danger fill. With a static palette you can get away
    // with hardcoding a dark value, but matugen flips these with the
    // wallpaper, so they have to come from the scheme too.
    readonly property color accent: "{{colors.primary.default.hex}}"
    readonly property color accentFg: "{{colors.on_primary.default.hex}}"
    readonly property color danger: "{{colors.error.default.hex}}"
    readonly property color dangerFg: "{{colors.on_error.default.hex}}"
    readonly property color warn: "{{colors.tertiary.default.hex}}"
}
