# Starship Matugen Theme
format = """
[](fg:#ffb691)\
$directory\
[](fg:#ffb691 bg:#5c4032)\
$git_branch\
$git_status\
[](fg:#5c4032 bg:#4c481c)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#4c481c)\
$fill\
$time\
\n$character"""

[fill]
symbol = " "

[character]
success_symbol = "[❯](bold #ffb691)"
error_symbol = "[❯](bold #ffb4ab)"

[directory]
style = "fg:#542202 bg:#ffb691"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#ffdbcb bg:#5c4032"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#ffdbcb bg:#5c4032"
format = '[[($all_status$ahead_behind )]($style)]($style)'

[nodejs]
symbol = ""
style = "fg:#ece4aa bg:#4c481c"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#ece4aa bg:#4c481c"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "fg:#ece4aa bg:#4c481c"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
style = "fg:#ece4aa bg:#4c481c"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R"
style = "fg:#d7c2b9"
format = '[  $time ]($style)'
