general {
    lock_cmd = pidof hyprlock || hyprlock       
    before_sleep_cmd = loginctl lock-session    
    after_sleep_cmd = hyprctl dispatch dpms on  
}

# 1. Dim screen (4.3 minutes = 258s)
listener {
    timeout = 258                                
    on-timeout = brightnessctl -s set 10%         
    on-resume = brightnessctl -r                  
}

# 2. Turn off screen (6 minutes = 360s)
listener {
    timeout = 360                                
    on-timeout = hyprctl dispatch dpms off       
    on-resume = hyprctl dispatch dpms on         
}

# 3. Lock session (6 minutes 30 seconds = 390s)
listener {
    timeout = 390                                
    on-timeout = loginctl lock-session           
}
