$primary = rgb(c2c1ff)
$primary-container = rgb(414178)
$secondary = rgb(c6c4dd)
$tertiary = rgb(eab9d2)
$surface = rgb(131318)
$surface-container = rgb(1f1f25)
$error = rgb(ffb4ab)
$on-surface = rgb(e5e1e9)
$outline = rgb(918f9a)
