gestures {
    # https://wiki.hypr.land/Configuring/Gestures/ 
    # gesture = fingers, direction, action, options
    gesture = 3, horizontal, workspace
    gesture = 3, pinchout, fullscreen
}

input {
    kb_layout = pl,us
    kb_variant =
    kb_model =
    kb_options = #grp:win_space_toggle #to toggle on super+space
    kb_rules = 
    numlock_by_default = true

    follow_mouse = 0
    force_no_accel = 0
    force_no_accel = false

    touchpad {
        natural_scroll = no
    }


    sensitivity = -0.5 # -1.0 - 1.0, 0 means no modification.
}

