# █▀▀ ▀▄▀ █▀▀ █▀▀
# ██▄ █░█ ██▄ █▄▄

# Execute your favorite apps at launch
# Soemthign idk
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd --all
exec-once = xdg-desktop-portal-hyprland
exec-once = xdg-desktop-portal

# System notifications, wallpapers, and other utilities etc
exec-once = awww-daemon # wallpapers
exec-once = waybar
exec-once = dunst # notifications (similar to mako)
exec-once = blueman-applet
exec-once = nm-applet --indicator
exec-once = wl-paste --watch cliphist store
exec-once = hypridle
exec-once = awww img /home/cl1ngz/Pictures/CurrnetActiveWallpaper/a_road_leading_to_a_city.jpg

# Apps startup
# exec-once =  soimethign here
