# █▀▀ ▀▄▀ █▀▀ █▀▀
# ██▄ █░█ ██▄ █▄▄

# Execute your favorite apps at launch
# exec-once = ~/.config/hypr/xdg-portal-hyprland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd --all
exec-once = xdg-desktop-portal-hyprland
exec-once = xdg-desktop-portal
#exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = awww-daemon
exec-once = 	waybar
exec-once = dunst #mako
exec-once = blueman-applet
exec-once = nm-applet --indicator
exec-once = wl-paste --watch cliphist store
exec-once = hypridle
exec-once = awww img /home/cl1ngz/Pictures/CurrnetActiveWallpaper/a_road_leading_to_a_city.jpg


# Apps startup
# exec-once = superproductivity
