# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█


# Example windowrule
# windowrule=RULE,PARAMETERS
# windowrule = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Animations
# windowrule animation popin, match:class ^(kitty)$, match:title ^(update-sys)$
# windowrule animation popin, match:class ^(thunar)$
# windowrule animation popin, match:class ^(discord)$
# windowrule animation popin, match:class ^(chromium)$

# Opacity 
windowrule = opacity 0.75 0.75, match:class ^(kitty)$
windowrule = opacity 0.71 0.71, match:class ^(discord)$
windowrule = opacity 0.91 0.91, match:class ^(code-oss)$
windowrule = opacity 0.9 0.9, match:class ^(jetbrains-idea-ce)$
windowrule = move cursor -3% -105%, match:class ^(rofi)$
windowrule = no_anim on, match:class ^(rofi)$
windowrule = opacity 0.8 0.6, match:class ^(rofi)$

# Position
windowrule = float on, match:class (pavucontrol)$
windowrule = float on, match:class (blueman-manager)$
windowrule = float on, match:class (nm-connection-editor)$
windowrule = float on, match:class (chromium)$
windowrule = float on, match:title (btop)$
windowrule = float on, match:title (update-sys)$
windowrule = float on, match:title (Oracle VM VirtualBox Manager)$
windowrule = float on, match:title (VirtualBox - Preferences)$
windowrule = float on, match:class (steam)$
windowrule = fullscreen on, match:class ^(superProductivity)$
# windowrule = fullscreen, match:class ^(zen)$
windowrule = float on, match:class (imv)$
windowrule = center on, match:class (imv)$
windowrule = size 900 600, match:class (imv)$

# Workspace 
# windowrule = workspace 1, class:^()$
windowrule = workspace 2, match:class (zen)$
windowrule = workspace 3, match:class (thunar)$
windowrule = workspace 4, match:class (code-oss)$
windowrule = workspace 4, match:class (jetbrains-idea)$
windowrule = workspace 5, match:class (vesktop)$
windowrule = workspace 5, match:class (calibre-gui)$
windowrule = workspace 6, match:class (obsidian)$
windowrule = workspace 7, match:class (virt-manager)$
windowrule = workspace 6, match:class (localsend)$
windowrule = workspace 8, match:class (thunderbird)$
windowrule = workspace 8, match:class (org.qbittorrent.qBittorrent)$
windowrule = workspace 9, match:class (superProductivity)$
windowrule = workspace 10, match:class (KeePassXC)$
windowrule = workspace 10, match:class (org.keepassxc.KeePassXC)$


# Size
# windowrule = size 800 600,class:^(download)$
# windowrule = size 800 600,title:^(Open File)$
# windowrule = size 800 600,title:^(Save File)$
# windowrule = size 800 600,title:^(Volume Control)$
windowrule = size 380 720, match:title (Friends List)$


# windowrule = idleinhibit focus,class:^(mpv)$
# windowrule = idleinhibit fullscreen,class:^(Brave-browser)$

# xwaylandvideobridge
windowrule = opacity 0.0 override 0.0 override, match:class (xwaylandvideobridge)$
windowrule = no_anim on, match:class (xwaylandvideobridge)$
windowrule = no_focus on, match:class (xwaylandvideobridge)$
windowrule = no_initial_focus on, match:class (xwaylandvideobridge)$

# windowrule = float on, match:class (org.godotengine.Editor)$

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
