import QtQuick
import QtQuick.Layouts
import Quickshell
import Quickshell.Wayland
import Quickshell.Io
import qs

PanelWindow {
    id: powerWindow

    anchors {
        top: true
        bottom: true
        left: true
        right: true
    }

    WlrLayershell.layer: WlrLayer.Overlay
    WlrLayershell.keyboardFocus: WlrKeyboardFocus.Exclusive
    WlrLayershell.namespace: "quickshell-powermenu"

    color: "transparent"

    // Palette comes from Colors.qml, generated by matugen.
    // Kept as local aliases so the rest of the file is unchanged.
    readonly property color base: Colors.base
    readonly property color mantle: Colors.mantle
    readonly property color surface0: Colors.surface0
    readonly property color surface1: Colors.surface1
    readonly property color outline: Colors.outline
    readonly property color textMain: Colors.textMain
    readonly property color textDim: Colors.textDim
    readonly property color textFaint: Colors.textFaint
    readonly property color accent: Colors.accent
    readonly property color accentFg: Colors.accentFg
    readonly property color danger: Colors.danger
    readonly property color dangerFg: Colors.dangerFg
    readonly property color warn: Colors.warn

    readonly property string iconFont: "JetBrains Mono Nerd Font"

    // Your rofi menu fires immediately on select. Powering off by mistake
    // is a worse outcome than clearing a clipboard entry by mistake, so
    // destructive actions arm on the first press and run on the second.
    // Set this to false for exact parity with the rofi behaviour.
    property bool confirmDestructive: true

    // ---- actions -----------------------------------------------------
    // Order matches the rofi script: lock, logout, suspend, shutdown, reboot.
    readonly property var actions: [
        { glyph: "󰌾", name: "Lock",      verb: "lock the session", key: "l", destructive: false, cmd: ["loginctl", "lock-session"] },
        { glyph: "󰍃", name: "Log out",   verb: "log out",          key: "e", destructive: true,  cmd: ["hyprctl", "dispatch", "exit"] },
        { glyph: "󰤄", name: "Suspend",   verb: "suspend",          key: "s", destructive: false, cmd: ["systemctl", "suspend"] },
        { glyph: "", name: "Shut down", verb: "shut down",        key: "p", destructive: true,  cmd: ["systemctl", "poweroff"] },
        { glyph: "󰜉", name: "Restart",   verb: "restart",          key: "r", destructive: true,  cmd: ["systemctl", "reboot"] }
    ]

    property int selectedIndex: 0
    property int armedIndex: -1      // destructive action awaiting a second press
    property bool running: false     // an action has fired; ignore further input

    function selectedAction() {
        return actions[selectedIndex];
    }

    function moveSelection(delta) {
        if (running) return;
        armedIndex = -1;
        let next = selectedIndex + delta;
        // Wrap: five tiles in a row, and wrapping is what you expect from
        // a horizontal picker of this size.
        if (next < 0) next = actions.length - 1;
        if (next >= actions.length) next = 0;
        selectedIndex = next;
    }

    function activate(index) {
        if (running || index < 0 || index >= actions.length) return;
        const action = actions[index];

        if (confirmDestructive && action.destructive && armedIndex !== index) {
            selectedIndex = index;
            armedIndex = index;
            return;
        }

        armedIndex = -1;
        selectedIndex = index;
        running = true;
        actionProcess.run(action.cmd);
    }

    function activateByKey(text) {
        if (running) return false;
        for (let i = 0; i < actions.length; i++) {
            if (actions[i].key === text) { activate(i); return true; }
        }
        return false;
    }

    // ---- processes ---------------------------------------------------

    // Waits for the command to exit before quitting. Quitting first would
    // tear down the process we just spawned, which matters for the ones
    // that don't take the session down with them (lock, suspend).
    Process {
        id: actionProcess

        function run(cmd) {
            command = cmd;
            running = true;
            quitFallback.restart();
        }

        onExited: Qt.quit()
    }

    // If a command hangs, don't leave the overlay stuck on screen holding
    // an exclusive keyboard grab.
    Timer {
        id: quitFallback
        interval: 4000
        onTriggered: Qt.quit()
    }

    property string uptimeText: ""

    Process {
        id: uptimeProcess
        running: true
        command: ["sh", "-c", "uptime -p | sed -e 's/up //'"]
        stdout: StdioCollector {
            onStreamFinished: powerWindow.uptimeText = text.trim()
        }
    }

    Timer {
        interval: 60000
        repeat: true
        running: true
        onTriggered: {
            uptimeProcess.running = false;
            uptimeProcess.running = true;
        }
    }

    // ==================================================================
    // UI
    // ==================================================================

    FocusScope {
        anchors.fill: parent
        focus: true
        Component.onCompleted: forceActiveFocus()

        Keys.onLeftPressed: powerWindow.moveSelection(-1)
        Keys.onRightPressed: powerWindow.moveSelection(1)
        Keys.onPressed: (event) => {
            switch (event.key) {
            case Qt.Key_Escape:
                if (powerWindow.armedIndex !== -1) powerWindow.armedIndex = -1;
                else Qt.quit();
                event.accepted = true;
                return;
            case Qt.Key_Return:
            case Qt.Key_Enter:
            case Qt.Key_Space:
                powerWindow.activate(powerWindow.selectedIndex);
                event.accepted = true;
                return;
            case Qt.Key_H:
                powerWindow.moveSelection(-1);
                event.accepted = true;
                return;
            case Qt.Key_Tab:
                powerWindow.moveSelection(1);
                event.accepted = true;
                return;
            case Qt.Key_Home:
                powerWindow.selectedIndex = 0;
                powerWindow.armedIndex = -1;
                event.accepted = true;
                return;
            case Qt.Key_End:
                powerWindow.selectedIndex = powerWindow.actions.length - 1;
                powerWindow.armedIndex = -1;
                event.accepted = true;
                return;
            }
            // Single-letter shortcuts (l/e/s/p/r). Checked after the keys
            // above so "l" can still mean "move right" in the vim pair.
            if (event.text === "l" && powerWindow.selectedAction().key !== "l") {
                powerWindow.moveSelection(1);
                event.accepted = true;
                return;
            }
            if (powerWindow.activateByKey(event.text)) event.accepted = true;
        }

        // Click-outside dismisses.
        MouseArea {
            anchors.fill: parent
            onClicked: {
                if (powerWindow.armedIndex !== -1) { powerWindow.armedIndex = -1; return; }
                Qt.quit();
            }
        }

        Rectangle {
            id: card
            anchors.centerIn: parent
            implicitWidth: 700
            implicitHeight: cardColumn.implicitHeight + 36

            color: powerWindow.base
            radius: 16
            border.width: 1
            border.color: powerWindow.outline

            opacity: 0
            scale: 0.97
            Component.onCompleted: { opacity = 1; scale = 1; }
            Behavior on opacity { NumberAnimation { duration: 160; easing.type: Easing.OutCubic } }
            Behavior on scale { NumberAnimation { duration: 200; easing.type: Easing.OutBack } }

            // Swallow clicks so they don't reach the dismiss backdrop.
            MouseArea { anchors.fill: parent }

            ColumnLayout {
                id: cardColumn
                anchors.left: parent.left
                anchors.right: parent.right
                anchors.verticalCenter: parent.verticalCenter
                anchors.leftMargin: 18
                anchors.rightMargin: 18
                spacing: 14

                // ---- header: uptime left, current action right ----
                RowLayout {
                    Layout.fillWidth: true
                    Layout.topMargin: 4
                    spacing: 12

                    Text {
                        text: powerWindow.uptimeText === "" ? "Uptime: —" : "Uptime: " + powerWindow.uptimeText
                        font.pixelSize: 14
                        color: powerWindow.textDim
                    }

                    Item { Layout.fillWidth: true }

                    Text {
                        readonly property bool armed: powerWindow.armedIndex === powerWindow.selectedIndex
                        text: powerWindow.running
                            ? powerWindow.selectedAction().name + "…"
                            : (armed ? "Press again to " + powerWindow.selectedAction().verb
                                     : powerWindow.selectedAction().name)
                        font.pixelSize: 14
                        font.weight: armed ? Font.DemiBold : Font.Normal
                        color: armed ? powerWindow.danger : powerWindow.textFaint
                        Behavior on color { ColorAnimation { duration: 140 } }
                    }
                }

                // ---- the five tiles ----
                RowLayout {
                    Layout.fillWidth: true
                    spacing: 15

                    Repeater {
                        model: powerWindow.actions

                        delegate: Rectangle {
                            id: tile
                            required property var modelData
                            required property int index

                            readonly property bool selected: powerWindow.selectedIndex === index
                            readonly property bool armed: powerWindow.armedIndex === index
                            readonly property color fillColor: armed ? powerWindow.danger : powerWindow.accent

                            Layout.fillWidth: true
                            Layout.preferredHeight: 140

                            radius: 12
                            color: selected ? fillColor
                                 : tileMouse.containsMouse ? powerWindow.surface0
                                 : powerWindow.mantle
                            border.width: 1
                            border.color: selected ? fillColor : powerWindow.outline
                            scale: tileMouse.pressed ? 0.96 : 1.0

                            Behavior on color { ColorAnimation { duration: 130; easing.type: Easing.OutCubic } }
                            Behavior on border.color { ColorAnimation { duration: 130; easing.type: Easing.OutCubic } }
                            Behavior on scale { NumberAnimation { duration: 100; easing.type: Easing.OutCubic } }

                            Text {
                                anchors.centerIn: parent
                                text: tile.modelData.glyph
                                font.family: powerWindow.iconFont
                                font.pixelSize: 48
                                color: tile.selected ? (tile.armed ? powerWindow.dangerFg : powerWindow.accentFg) : powerWindow.textMain
                                Behavior on color { ColorAnimation { duration: 130 } }
                            }

                            // The key that triggers this tile, in the corner.
                            // Doubles as the only label the tiles need.
                            Text {
                                anchors.top: parent.top
                                anchors.right: parent.right
                                anchors.topMargin: 10
                                anchors.rightMargin: 12
                                text: tile.modelData.key
                                font.family: powerWindow.iconFont
                                font.pixelSize: 12
                                color: tile.selected ? Qt.alpha(tile.armed ? powerWindow.dangerFg : powerWindow.accentFg, 0.55) : powerWindow.textFaint
                                Behavior on color { ColorAnimation { duration: 130 } }
                            }

                            MouseArea {
                                id: tileMouse
                                anchors.fill: parent
                                hoverEnabled: true
                                onEntered: {
                                    if (powerWindow.running) return;
                                    if (powerWindow.selectedIndex !== tile.index) powerWindow.armedIndex = -1;
                                    powerWindow.selectedIndex = tile.index;
                                }
                                onClicked: powerWindow.activate(tile.index)
                            }
                        }
                    }
                }
            }
        }
    }
}
